### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by Antoinebr** [lambtron/linkedinbot#3]
Hi :)
When i lunch the script i have this message :
Error opening url "https://www.linkedin.com/uas/login": SSL handshake failed

any idea ?

**Comment by Antoinebr** [comment]
Seems to be ok with 

--ssl-protocol=any scraper.js

**Comment by lambtron** [comment]
Hmm this repo is really old and hasn't been maintained in over a year. Sorry about that! I probably don't have time either to diagnose it, but i would recommend building your own using this Nightmare plugin:

https://github.com/lambtron/nightmare-linkedin
